theme:  jekyll-theme-minimal
title:  Heather M. Kopp
description: |
    Assistant Professor <br>
    Department of Political Science <br>
    Texas Tech University <br>
    Lubbock, TX 79409 <br>
    <a href="mailto:hkopp@ttu.edu">hkopp@ttu.edu</a> 
logo: assets/images/kopp.jpg
show_downloads: false
