theme: jekyll-theme-minimal
title: Name name
description: Title <br> University <br> Office: <br> Email: 
logo: https://plus.unsplash.com/premium_photo-1669357657851-f15e1417ea08?w=700&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8cGxhbnR8ZW58MHx8MHx8fDA%3D
show_downloads: false
